apiVersion: v1
kind: Service
metadata:
  name: kube-redis-service
spec:
  ports:
  - port: 6379
    nodePort: 31082
  selector:
    app: kube-redis
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-redis
spec:
  selector:
    matchLabels:
      app: kube-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kube-redis
    spec:
      containers:
      - image: redis:4.0.11-alpine
        name: kube-redis
        args:
        - "--requirepass aa"
        ports:
        - containerPort: 6379
          name: kube-redis
      nodeSelector:
        nodeType: service
